JOB_SECTORS = {
ACCOUNTANCY : "Accountancy",
ADMINISTRATION : "Administration",
ADVERTISING : "Advertising",
AEROSPACE : "Aerospace",
APPRENTICESHIPS : "Apprenticeships",
AUTOMOTIVE : "Automotive",
BANKING : "Banking",
CALL_CENTRE : "Call Centre",
CATERING : "Catering",
CHARITY : "Charity",
CONSTRUCTION : "Construction",
CREATIVE : "Creative",
CUSTOMER_SERVICE : "Customer Service",
EDUCATION : "Education",
ENGINEERING : "Engineering",
FINANCE : "Finance",
FMCG : "FMCG",
GRADUATE : "Graduate",
HEALTHCARE : "Healthcare",
HOSPITALITY : "Hospitality",
HR : "HR",
INSURANCE : "Insurance",
IT : "IT",
LEGAL : "Legal",
LEISURE : "Leisure",
LOGISTICS : "Logistics",
MANAGEMENT_CONSULTANCY : "Management Consultancy",
MANUFACTURING : "Manufacturing",
MARKETING : "Marketing",
MEDIA : "Media",
NURSING : "Nursing",
OIL_AND_GAS : "Oil and Gas",
PA : "PA",
PART_TIME : "Part time",
PHARMACEUTICAL : "Pharmaceutical",
PR : "PR",
PROPERTY : "Property",
PUBLIC_SECTOR : "Public Sector",
RECRUITMENT_SALES : "Recruitment Sales",
RENEWABLE_ENERGY : "Renewable Energy",
RETAIL : "Retail",
SALES : "Sales",
SCIENCE : "Science",
SENIOR_APPOINTMENTS : "Senior Appointments",
SOCIAL_WORK : "Social Work",
TEACHING : "Teaching",
TELECOMS : "Telecoms",
TEMPORARY : "Temporary",
TOURISM : "Tourism",
TRANSPORT : "Transport",
TRAVEL : "Travel",
UTILITIES : "Utilities",
WHOLESALE : "Wholesale"
}
